language: node_js

os:
  - linux

branches:
  only:
    - develop
    - task/#29-travis-ci

node_js:
  - "6"

before_script:
  - npm install
  - echo 'America/Chicago' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

notifications:
  email:
    on_success: never
    on_failure: change

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb
